// vue-example-dont-run/src/components/CustomNodeTypeModal.vue
<template>
	<div class="custom-node-crud-modal" v-if="visible">
		<div class="modal-bg" @click="close" />
		<div class="modal-content">
			<h3>{{ editId ? 'Editar tipo de nodo' : 'Nuevo tipo de nodo' }}</h3>
			<form @submit.prevent="save">
				<label
					>Nombre
					<input v-model="form.name" required maxlength="32" />
				</label>
				<label
					>Color
					<input v-model="form.color" type="color" />
				</label>
				<label
					>Icono (emoji o SVG)
					<input v-model="form.icon" placeholder="😀 o <svg .../>" />
				</label>
				<label
					>Descripción
					<input v-model="form.description" maxlength="64" />
				</label>
				<div class="actions">
					<button type="submit">{{ editId ? 'Actualizar' : 'Crear' }}</button>
					<button type="button" @click="close">Cancelar</button>
				</div>
			</form>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, watch, defineProps, defineEmits } from 'vue';
import type { CustomNodeType } from '../stores/nodeTypes';

const props = defineProps<{
	visible: boolean;
	editId?: string | null;
	nodeType?: Partial<CustomNodeType>;
}>();
const emit = defineEmits(['close', 'save']);

const form = ref({
	name: '',
	color: '#e14d43',
	icon: '',
	description: '',
});

watch(
	() => props.nodeType,
	(val) => {
		if (val) Object.assign(form.value, val);
		else form.value = { name: '', color: '#e14d43', icon: '', description: '' };
	},
	{ immediate: true },
);

function save() {
	emit('save', { ...form.value, id: props.editId });
}
function close() {
	emit('close');
}
</script>

<style scoped>
.custom-node-crud-modal {
	position: fixed;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 9999;
}
.modal-bg {
	position: absolute;
	inset: 0;
	background: rgba(0, 0, 0, 0.35);
}
.modal-content {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	background: #23272e;
	color: #fff;
	border-radius: 12px;
	padding: 28px 24px 18px 24px;
	min-width: 320px;
	box-shadow: 0 4px 32px 0 #0008;
}
.modal-content h3 {
	margin: 0 0 18px 0;
	font-size: 1.2rem;
}
label {
	display: block;
	margin-bottom: 12px;
	font-size: 1rem;
}
input[type='text'],
input[type='color'],
input[type='email'],
input[type='number'],
input[type='password'] {
	width: 100%;
	margin-top: 4px;
	padding: 6px 8px;
	border-radius: 6px;
	border: 1.5px solid #fff2;
	background: #181c20;
	color: #fff;
	font-size: 1rem;
	outline: none;
	transition: border 0.2s;
}
input[type='color'] {
	width: 40px;
	height: 32px;
	padding: 0;
	border: none;
	background: none;
}
.actions {
	display: flex;
	gap: 10px;
	margin-top: 10px;
}
button {
	background: #ffb84d;
	color: #23272e;
	border: none;
	border-radius: 6px;
	padding: 7px 18px;
	font-weight: bold;
	cursor: pointer;
	font-size: 1rem;
	transition: background 0.18s;
}
button[type='button'] {
	background: #31343b;
	color: #fff;
}
button:hover {
	background: #ffcb7d;
}
</style>

// src/components/CustomNodeTypeModal.tsx
import React, { useState, useEffect } from 'react';
import { Button, Input, Form, ColorPicker } from 'antd';
import type { Color } from 'antd/es/color-picker';
import './CustomNodeTypeModal.css';

interface CustomNodeType {
  id?: string;
  name: string;
  color: string;
  icon: string;
  description: string;
}

interface CustomNodeTypeModalProps {
  visible: boolean;
  editId?: string | null;
  nodeType?: Partial<CustomNodeType>;
  onClose: () => void;
  onSave: (nodeType: CustomNodeType) => void;
}

const CustomNodeTypeModal: React.FC<CustomNodeTypeModalProps> = ({
  visible,
  editId = null,
  nodeType,
  onClose,
  onSave,
}) => {
  const [form, setForm] = useState<CustomNodeType>({
    name: '',
    color: '#e14d43',
    icon: '',
    description: '',
  });

  // Reset form when nodeType changes
  useEffect(() => {
    if (nodeType) {
      setForm({
        name: nodeType.name || '',
        color: nodeType.color || '#e14d43',
        icon: nodeType.icon || '',
        description: nodeType.description || '',
      });
    } else {
      setForm({
        name: '',
        color: '#e14d43',
        icon: '',
        description: '',
      });
    }
  }, [nodeType]);

  const handleSave = () => {
    onSave({ ...form, id: editId || undefined });
  };

  const handleColorChange = (color: Color) => {
    setForm({ ...form, color: color.toHexString() });
  };

  if (!visible) return null;

  return (
    <div className="custom-node-crud-modal">
      <div className="modal-bg" onClick={onClose} />
      <div className="modal-content">
        <h3>{editId ? 'Editar tipo de nodo' : 'Nuevo tipo de nodo'}</h3>
        <Form layout="vertical" onFinish={handleSave}>
          <Form.Item label="Nombre" required>
            <Input 
              value={form.name} 
              onChange={e => setForm({ ...form, name: e.target.value })}
              required
              maxLength={32}
            />
          </Form.Item>
          
          <Form.Item label="Color">
            <ColorPicker 
              value={form.color}
              onChange={handleColorChange}
            />
          </Form.Item>
          
          <Form.Item label="Icono (emoji o SVG)">
            <Input 
              value={form.icon} 
              onChange={e => setForm({ ...form, icon: e.target.value })}
              placeholder="😀 o <svg .../>"
            />
          </Form.Item>
          
          <Form.Item label="Descripción">
            <Input 
              value={form.description} 
              onChange={e => setForm({ ...form, description: e.target.value })}
              maxLength={64}
            />
          </Form.Item>
          
          <div className="actions">
            <Button type="primary" htmlType="submit">
              {editId ? 'Actualizar' : 'Crear'}
            </Button>
            <Button onClick={onClose}>Cancelar</Button>
          </div>
        </Form>
      </div>
    </div>
  );
};

export default CustomNodeTypeModal;
